name: Generate Zombie Hacker Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # daily update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Generate contributions data
        run: node scripts/fetchContributions.js

      - name: Build zombie hacker visual
        run: node scripts/generateZombieHtml.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
